# Generated by Django 4.2 on 2023-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rucs',
            fields=[
                ('ruc', models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('estado_del_contribuyente', models.CharField(max_length=255)),
                ('condicion_de_domicilio', models.CharField(max_length=255)),
                ('ubigeo', models.CharField(max_length=255)),
                ('tipo_via', models.CharField(max_length=255)),
                ('nombre_via', models.CharField(max_length=255)),
                ('codigo_zona', models.CharField(max_length=255)),
                ('tipo_zona', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('interior', models.CharField(max_length=255)),
                ('lote', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('manzana', models.CharField(max_length=255)),
                ('kilometro', models.CharField(max_length=255)),
            ],
        ),
    ]
